version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: cielo-selenium
    ports:
      - "4444:4444"
      - "7900:7900" # VNC (sem senha por padrão nas imagens recentes, ou verifique documentação)
    shm_size: "2gb" # Importante para evitar crashes do Chrome em container

  tests:
    build: .
    container_name: cielo-tests
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    depends_on:
      - selenium
    volumes:
      - ./target:/app/target # Para acessar reports/screenshots após execução
