apiVersion: batch/v1
kind: Job
metadata:
  name: cielo-testes-job
  labels:
    app: cielo-testes
spec:
  template:
    metadata:
      labels:
        app: cielo-testes
    spec:
      containers:
      - name: cielo-testes
        image: cielo-testes:latest
        imagePullPolicy: IfNotPresent
        command: ["mvn", "test"]
        env:
        - name: SELENIUM_REMOTE_URL
          value: "http://localhost:4444/wd/hub" # Localhost funciona pois containers no mesmo Pod compartilham rede
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      
      # Sidecar Container para o Browser
      - name: selenium-chrome
        image: selenium/standalone-chrome:latest
        ports:
        - containerPort: 4444
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      
      restartPolicy: Never
  backoffLimit: 1
